env:
  TERM: xterm-256color
window:
  dimensions:
    columns: 270
    lines: 85
  opacity: 0.99
  blur: true
  decorations: "Buttonless"
  title: Alacritty
font:
  normal:
    # family: "MesloLGS NF"
    # family: "Monaspace Argon"
    # family: "Monaspace Neon"
    family: "Monaspace Xenon"
    # family: "FiraCode Nerd Font"
    # family: "Hack Nerd Font"
    style: Regular
  bold:
    # family: "MesloLGS NF"
    # family: "FiraCode Nerd Font"
    family: "Monaspace Xenon"
    style: Bold
  italic:
    # family: "MesloLGS NF"
    # family: "FiraCode Nerd Font"
    family: "Monaspace Xenon"
    style: Italic
  size: 14
shell:
  program: /bin/zsh
selection:
  save_to_clipboard: true
key_bindings:
  # move word using Alt/Opt key
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left, mods: Alt, chars: "\x1BB" }
  # tmux preview all windows - Removed, potentially conflicting
  # - { key: L, mods: Command, chars: "\x01\x77" }
  # tmux preview all sessions - Removed, potentially conflicting
  # - { key: K, mods: Command, chars: "\x01\x73" }
  # sesh inside tmux
  - { key: K, mods: Command, chars: "\x01\x54" }
  # Increase font size
  - { key: Plus, mods: Command, chars: "\x11" }
  # Decrease font size
  - { key: Minus, mods: Command, chars: "\x0F" }
