[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Jetbrain Mono"
# family = "Monaspace Xenon"
# family = "MesloLGS NF"
# family: "MesloLGS NF"
# family: "Monaspace Argon"
# family: "Monaspace Neon"
# family: "FiraCode Nerd Font"
# family: "Hack Nerd Fontfamily = "Monaspace Xenon"

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
opacity = 1
option_as_alt = "Both"
dimensions = { columns = 270, lines = 85}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "L", mods = "Command", chars = "\u0001w" },
  { key = "K", mods = "Command", chars = "\u0001T" },
]
