# # https://docs.rs/glutin/0.28.0/glutin/event/enum.VirtualKeyCode.html#variants
#
window:
# #   Window dimensions (changes require restart)
#
# #   Number of lines/columns (not pixels) in the terminal. The number of columns
# #   must be at least `2`, while using a value of `0` for columns and lines will
# #   fall back to the window manager's recommended size.
  dimensions:
   columns: 270
   lines: 85
  opacity: 1
font:
  normal:
    family: "MesloLGS NF"
  size: 11
shell:
 program: /usr/bin/zsh
working_directory: /home/azuan/Workspace
# selection:
#   save_to_clipboard: true
# cursor:
#   style: Beam
#
