env:
  TERM: xterm-256color
window:
  dimensions:
   columns: 270
   lines: 85
  opacity: 1
font:
  normal:
    family: "MesloLGS NF"
  size: 14
shell:
 program: /bin/zsh
selection:
  save_to_clipboard: true
key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  # preview all windows
  - { key: L, mods: Command, chars: "\x01\x77" }
  # preview all sessions
  - { key: K, mods: Command, chars: "\x01\x73" }
