env:
  TERM: xterm-256color
window:
  dimensions:
   columns: 270
   lines: 85
  opacity: 1
font:
  normal:
    family: "MesloLGS NF"
  size: 14
shell:
 program: /bin/zsh
selection:
  save_to_clipboard: true
