return {
  -- "nvim-telescope/telescope.nvim",
  -- branch = "0.1.x",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  --   "nvim-tree/nvim-web-devicons",
  --   "camgraff/telescope-tmux.nvim",
  -- },
  -- config = function()
  --   local telescope = require("telescope")
  --   local actions = require("telescope.actions")
  --
  --   telescope.setup({
  --     defaults = {
  --       file_ignore_patterns = { "%.git", "node_modules" },
  --       sorting_strategy = "ascending",
  --       layout_strategy = "horizontal",
  --       layout_config = {
  --         horizontal = {
  --           prompt_position = "top",
  --           width = { padding = 0 },
  --           height = { padding = 0 },
  --           preview_width = 0.6,
  --         },
  --       },
  --       -- path_display = { "truncate " },
  --       path_display = { "filename_first" },
  --       mappings = {
  --         i = {
  --           ["<esc>"] = actions.close,
  --           ["<C-k>"] = actions.move_selection_previous, -- move to prev result
  --           ["<C-j>"] = actions.move_selection_next, -- move to next result
  --           ["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
  --         },
  --       },
  --     },
  --     extensions = {
  --       fzf = {
  --         fuzzy = true, -- false will only do exact matching
  --         override_generic_sorter = true, -- override the generic sorter
  --         override_file_sorter = true, -- override the file sorter
  --         case_mode = "ignore_case", -- or "ignore_case" or "respect_case"
  --         -- the default case_mode is "smart_case"
  --       },
  --     },
  --     pickers = {
  --       lsp_references = {
  --         show_line = false,
  --       },
  --     },
  --   })
  --
  --   telescope.load_extension("fzf")
  --   telescope.load_extension("tmux")
  -- end,
}
