shell-integration       = zsh
macos-titlebar-style    = hidden
macos-option-as-alt     = true
font-family             = Jetbrain Mono
mouse-hide-while-typing = true
scrollback-limit        = 1000000

keybind                 = super+k=text:\x01\x54
keybind                 = super+r=reload_config
confirm-close-surface   = false

# keybind                 = alt+left=unbind
# keybind                 = alt+right=unbind
# keybind = ctrl+h=goto_split:left
# keybind = ctrl+j=goto_split:bottom
# keybind = ctrl+k=goto_split:top
# keybind = ctrl+l=goto_split:right

# keybind = ctrl+a>h=new_split:left
# keybind = ctrl+a>j=new_split:down
# keybind = ctrl+a>k=new_split:up
# keybind = ctrl+a>l=new_split:right
# keybind = ctrl+a>f=toggle_split_zoom

# keybind = ctrl+a>n=next_tab
# keybind = ctrl+a>p=previous_tab

window-save-state = always