-- require("luasnip.loaders.from_vscode").lazy_load()
--
-- -- nvim-cmp setup
-- local ls = require("luasnip")
--
-- ls.config.set_config {
--   history = false,
--   updateevents = "TextChanged,TextChangedI",
--   enable_autosnippets = true,
-- }
