# Open hyperlinked text files (for example, from eza) in Neovim.
protocol file
mime text/*
action launch --type=overlay --cwd=current -- ${EDITOR} -u ${HOME}/.config/nvim/scrollback.lua -- ${FILE_PATH}
