# model: openrouter/deepseek/deepseek-r1
model: gemini/gemini-2.5-flash-preview-04-17
editor-model: openrouter/anthropic/claude-3.5-sonnet
dark-mode: true
auto-commits: false
show-model-warnings: false
architect: true
yes-always: true
llm-history-file: .aider.llm.history
analytics-disable: true
watch-files: true
